language: python
python: "3.8"
install:
  - pip install -r requirements.txt
script:
  - export telegram_url=$telegram_url
  - export telegram_token=$telegram_token
  - export telegram_chatid=$telegram_chatid
  - export telegram_command=$telegram_command
  - python3 telegram.py
